# Generated by Django 4.1.4 on 2022-12-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(default='ambajogai', max_length=200),
            preserve_default=False,
        ),
    ]
