# Generated by Django 4.1.4 on 2022-12-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='large',
            field=models.ImageField(default='1.jpeg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myimage',
            name='mediam',
            field=models.ImageField(default='asjdfl', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myimage',
            name='thumbnail',
            field=models.ImageField(default='lksdjfl', upload_to=''),
            preserve_default=False,
        ),
    ]
