# Generated by Django 4.1.4 on 2022-12-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0002_myimage_large_myimage_mediam_myimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimage',
            name='large',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='mediam',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='thumbnail',
        ),
    ]
